- name: Install Docker
  shell: dnf install -y https://download.docker.com/linux/fedora/25/x86_64/stable/Packages/docker-ce-17.06.0.ce-1.fc25.x86_64.rpm

- name: Make sure Docker is running
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Add user 'fedora' to group 'docker'
  user: name=fedora groups=docker append=yes